### ISSUE TITLE
Change Social image of jobs pages

### ISSUE THREAD

**Issue by anjavanacker** [ordina-jworks/ordina-jworks.github.io#375] opened 2018-04-24 14:33 UTC
When I post a link from the job page, then the Angular logo is added.

Can we change it to the JWorks logo?

**Comment by Turbots** [comment] 2018-04-24 14:35
Add a `imagesocial` attribute to the _template.html file in the jobs folder

**Comment by gurtjun** [comment] 2018-04-24 17:15
Possible duplicate of #204?

**Comment by yannickdeturck** [comment] 2018-04-24 21:14
Appears to be working okay for LinkedIn? I tried old and new job positions and all of them had their own image being displayed as thumbnail.

**Comment by gurtjun** [comment] 2018-04-25 12:32
@yannickdeturck, I think @anjavanacker is talking about the general job page. As mentioned in #204 this has something to do with LinkedIn's caching for images. 

This can be solved by adding any query string to the url.  
`https://ordina-jworks.github.io/jobs/?jworks`

Result without query string:
![linkedin_without_hack](https://user-images.githubusercontent.com/13830735/39245753-e04ed6d8-4894-11e8-983e-aaa48a14a282.JPG)

Result with query string:
![linkedin_with_hack](https://user-images.githubusercontent.com/13830735/39245761-e48da4c2-4894-11e8-89ad-ad506ac8e816.JPG)

**Comment by yannickdeturck** [comment] 2018-04-25 12:48
@gurtjun Indeed, well noted. :-)

@anjavanacker, as Gert-jan said, it's due to LinkedIn's cache. Adding a query parameter (e.g.: https://ordina-jworks.github.io/jobs/?1) at the end of the url will force a new lookup of the image.

**Closed** 2018-04-26 10:45 UTC
